### PR TITLE
Fix make kamikaze.sh

### PR DESCRIPTION
**Pull request by goeland86**
Addressing #125

### CODE REVIEW

**Comment by eliasbakken** [comment]
This needs to be rebased on master after PR #130 has been merged.

**Comment by goeland86** [comment]
Why rebase? The history divergence is nill - I branched off from the code that was submitted in #130...

**Comment by eliasbakken** [comment]
OK, I guess since it was a PR towards master, I was seeing all changes in #130 as well as the changes in #131. Now that #130 is merged, the changes are more clear.

**Review by eliasbakken — APPROVED** [review]

**Comment by goeland86** [comment]
Oh, yeah. Sorry about that. I'll wait for the PR build to finish before merging.

**Pull request merged**
